swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


# transaction's endpoint

  /user/{userId}/accounts:
      get:
        tags:
          - Accounts Module
        summary: Account Types List
        description: API for retrieving a list of account types
        security:
        - Bearer: []
        parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: The unique identifier for the user
        produces:
          - application/json
        responses:
          '200':
            description: Successfully retrieved account types
            schema:
              type: array
              items:
                $ref: '#/definitions/AccountType'
          '400':
            description: Invalid request
          '500':
            description: Internal Server Error

  /user/{userId}/transactions/monthly:
      get:
        tags:
          - Transaction Module
        summary: Monthly Transactions List
        description: API for retrieving a list of transactions for the current month
        security:
          - Bearer: []
        parameters:
          - name: userId
            in: path
            required: true
            type: string
            description: The unique identifier for the user
        produces:
          - application/json
        responses:
          '200':
            description: Successfully retrieved monthly transactions
            schema:
              $ref: '#/definitions/MonthlyTransaction'
          '400':
            description: Invalid request
          '500':
            description: Internal Server Error
  /user/{userId}/transaction/{transactionId}:
    get:
      tags:
        - Transaction Detail Module
      summary: Transaction Details
      description: API for retrieving the details of a specific transaction
      security:
        - Bearer: []
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transaction details
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

  /user/{userId}/transaction/{transactionId}/update:
      put:
        tags:
          - Transaction Detail Module
        summary: Update Transaction Details
        description: API for updating category and note of a specific transaction
        security:
          - Bearer: []
        parameters:
          - name: userId
            in: path
            required: true
            type: string
          - name: transactionId
            in: path
            required: true
            type: string
          - in: body
            name: body
            description: New category and note for the transaction
            required: true
            schema:
              $ref: '#/definitions/TransactionUpdate'
        produces:
          - application/json
        responses:
          '200':
            description: Transaction details updated successfully
            schema:
              $ref: '#/definitions/TransactionUpdateResponse'
          '400':
            description: Invalid request
          '500':
            description: Internal Server Error

  /user/{userId}/transaction/{transactionId}/note/delete:
    delete:
      tags:
        - Transaction Detail Module
      summary: Delete Transaction Note
      description: API for deleting the note of a specific transaction
      security:
        - Bearer: []
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction note deleted successfully
        '400':
          description: Invalid request or transaction
        '500':
          description: Internal Server Error
          
#definition's references
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  AccountType:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the account type
        name:
          type: string
          description: Name of the account type
        description:
          type: string
          description: Description of the account type

  MonthlyTransaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction
      date:
        type: string
        format: date-time
        description: Date and time of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount involved in the transaction
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Optional note associated with the transaction
  
  TransactionDetails:
    type: object
    properties:
      transactionId:
        type: string
        description: Unique identifier of the transaction
      type:
        type: string
        description: Type of the transaction (e.g., debit, credit)
      category:
        type: string
        description: Category of the transaction
      amount:
        type: number
        format: float
        description: Amount involved in the transaction
      date:
        type: string
        format: date-time
        description: Date and time of the transaction
      note:
        type: string
        description: Optional note associated with the transaction

  TransactionUpdate:
      type: object
      required:
        - category
        - note
      properties:
        category:
          type: string
          description: New category of the transaction
        note:
          type: string
          description: New note associated with the transaction

  TransactionUpdateResponse:
    type: object
    properties:
      message:
        type: string
        description: A message confirming the successful update
      updatedTransaction:
        type: object
        properties:
          transactionId:
            type: string
          category:
            type: string
          note:
            type: string